# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20171117_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alias',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
